sudo: required
services:
  - docker

before_install:
  - docker build -t travis-build -f Dockerfile.dev .

script:
  - docker run travis-build npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  