sudo: required
services:
  - docker

before_install:
  - docker build -t pedroha/docker-react -f Dockerfile.dev .

script:
  - docker run pedroha/docker-react timeout -t 10 npm run test -- --ci --watchAll=false

